### ISSUE TITLE
Failed to match first line: ???

### ISSUE THREAD

**Issue by dzonatan** [vtnerd/monero-lws#10]
Trying to use this with mymonero app but can't find the way how to bypass this error:
![Screenshot from 2021-02-11 01-07-17](https://user-images.githubusercontent.com/5166666/107584833-d8a10680-6c05-11eb-98e3-96c3d4f9d9ff.png) 

Although, calling the API manually seems to be working.
Can't figure out why in mymonero case it doesn't work, any ideas?

**Comment by vtnerd** [comment]
What is the value for `--rest-server` ? Default?

**Comment by dzonatan** [comment]
`monero-lws-daemon --rest-server http://0.0.0.0:8443 --confirm-external-bind`

**Comment by vtnerd** [comment]
MyMonero app is trying to initiate a SSL connection, whereas `monero-lws` is immediately looking for a HTTP header. Starting with `--rest-server https://0.0.0.0:8443` will listen for SSL connections, but MyMonero app will likely reject unless you have a CA-signed (LetEncrypt, etc.) certificate.

Try:
 1. Listening for HTTPS connections to see how MyMonero app responds (override possible in UI?).
 2. See if MyMonero app accepts `http://` as a server input. I used to do this, but things have changed a bit since I last tried. I might need to download latest version myself. I think it may assume HTTPS, and only the hostname is configurable (I was changing the build itself).
 3. Ask MyMonero to somehow make this configurable.
 4. Get a signed cert.

The last points (3)&(4) are regrettable, but if MyMonero app requires HTTPS with a signed-certificate there is no code fix in `monero-lws` to get it working.

**Comment by vtnerd** [comment]
There's also DANE/TLSA. That would allow self-signed SSL certificates with fingerprints put in DNSSEC records. I think the OpenAlias support is client side, so MyMonero should already have DNSSEC support in clients. But adding DANE/TLSA is a bit more heavy lifting than they really want (there is no use for them directly).

**Comment by dzonatan** [comment]
Thanks for very detailed answer!

I've looked into mymonero codebase and it seems you're correct - they are stripping `http(s)://` prefix and forces to use `https://` under the hood.

Although this SSL topic is pretty foggy to me I had a success with a self-signed certificate from desktop client of mymonero. But not yet from the iOS version - having difficulties trusting the certificate, need to read more on that.

Anyway, thanks for the help! much appreciated! 🍻

**Comment by shermand100** [comment]
Hi @dzonatan 
Can you summarise or point me in the direction you took for monero-lws to accept a certificate when using MyMonero desktop please?
I've messed around with SSL for web pages in the past, but using them to get applications talking is new to me. Need a little nudge.

**Comment by dzonatan** [comment]
@shermand100 
1. You need a key and certificate. You can generate both of them using `openssl` through command line which can be a bit overwhelming to do if you haven't done it before. But you can find tutorials online.
2. The certificate needs to be self-trusted on machine where MyMonero will be used. Not sure what OS you use but again there are plenty of tutorials online how it can be done.

> 1 and 2 points can be done using https://github.com/FiloSottile/mkcert, although I haven't used it myself.

3. Start the daemon with ssl arguments: 
`monero-lws-daemon --rest-ssl-key my-cert.key rest-ssl-certificate my-cert.crt`

**Comment by trasherdk** [comment]
@shermand100 You could [Search GitHub for EasyRSA](https://github.com/search?o=desc&q=%2Feasyrsa&s=updated&type=Repositories) there are plenty of options to choose from.
