### ISSUE TITLE
monero-lws randomly crashes "Failed to send ZMQ RPC message"

### ISSUE THREAD

**Issue by dzonatan** [vtnerd/monero-lws#12]
From time to time (randomly but mostly within ~10 hours) the `monero-lws` crashes with the exact same sequence of logs:
![Screenshot from 2021-02-16 19-31-27](https://user-images.githubusercontent.com/5166666/108122213-9b78c080-70ac-11eb-8f8f-d9e6a1d722b2.png)
Although the `monerod` itself didn't print any errors - it's running the whole time.
Starting `monero-lws` right after the crash - works flawlessly till the next same error.

Seems like this timeout [provokes that](https://github.com/vtnerd/monero-lws/blob/f077953e02941e8e931a5f7aa870ced3b72a1f1e/src/scanner.cpp#L374) "Failed to send ZMQ RPC <...>" error.

EDIT: Regrading the timeout - this might be a real glitch on my network as I'm running `monerod` and `monero-lws` on separate machines. But I don't think that this should result into a crash in first place.

**Comment by vtnerd** [comment]
That error typically means that another `ZMQ-REQ` message was sent before the prior response was read. ZMQ only allows a single outstanding request for that socket type. Sending another message is a mistake here.

Does this connection drop out sometimes? Is the bandwidth low? Triggering the two-minute timeout here also seems odd. I'll try to come up with a fix shortly regardless.

**Comment by dzonatan** [comment]
> Is the bandwidth low?

Shouldn't be, everything is on the same local gigabit network.

> Does this connection drop out sometimes?

Not sure how can I check that, nothing else except this "Block retrieval timeout" can be found in the logs.
As soon as this warning comes out - it results into a "ZMQ RPC message" error.

**Comment by vtnerd** [comment]
I finally have a fix for this. It looks like I will just reset the entire scanner state, which isn't optimal, but this should be somewhat rare.

The problem was after sending data, there's no "ack" from ZeroMQ to determine if a remote node received the message (this likely complicates the ZeroMQ protocol). So there's no good way to determine: (1) if the message is being retried (no remote node to receive message), (2) if the message was received but then the node was terminated before responding, or (3) if the response is taking a long time.

**Comment by vtnerd** [comment]
This has been [pushed to develop](https://github.com/vtnerd/monero-lws/commit/346732014a19fe14bde70d98df1911b1a51fefb1). This will be cherry-picked to other branches if testing goes well.

**Comment by dzonatan** [comment]
Closing this as it's been running rock solid for quite a while now.
